"""
Twilio Service — outbound call initiation and TwiML construction.

Phase 2: Places calls, serves TwiML that opens a Media Stream WebSocket
         for bidirectional audio.
         NO welcome message from Twilio — the AI agent speaks entirely
         through the audio stream (Deepgram + TTS wired in Phase 3).
"""
from __future__ import annotations

import structlog
from twilio.rest import Client as TwilioClient
from twilio.twiml.voice_response import Connect, Stream, VoiceResponse

from app.config import settings
from app.models.session import SessionState

log = structlog.get_logger()


# ─── Client factory ───────────────────────────────────────────────────────────


def _twilio_client() -> TwilioClient | None:
    """Return a configured Twilio REST client, or None if credentials absent."""
    if not settings.TWILIO_ACCOUNT_SID or not settings.TWILIO_AUTH_TOKEN:
        log.warning("Twilio credentials not set — calls are disabled")
        return None
    return TwilioClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)


# ─── Outbound call ────────────────────────────────────────────────────────────


async def initiate_outbound_call(session: SessionState) -> str | None:
    """
    Place an outbound call to the customer via Twilio Programmable Voice.

    Returns the Twilio CallSid on success.
    Returns None if Twilio credentials are not configured (dev / test mode).
    Raises TwilioException on API errors.

    Twilio will:
      1. Dial the customer.
      2. On answer, GET/POST `twiml_url` → we return TwiML.
      3. TwiML opens a WebSocket Media Stream to `stream_url`.
      4. POST lifecycle events to `status_callback_url`.
    """
    client = _twilio_client()
    if not client:
        return None

    base = settings.AGENT_SERVICE_BASE_URL.rstrip("/")
    twiml_url = f"{base}/twilio/twiml/{session.session_id}"
    status_cb_url = f"{base}/twilio/callback/{session.session_id}"

    log.info(
        "placing outbound call",
        session_id=session.session_id,
        to=session.customer_phone,
        twiml_url=twiml_url,
    )

    call = client.calls.create(
        to=session.customer_phone,
        from_=settings.TWILIO_PHONE_NUMBER,
        url=twiml_url,
        method="GET",
        status_callback=status_cb_url,
        status_callback_method="POST",
        # Twilio status_callback_event valid values: initiated | ringing | answered | completed
        # The "completed" event covers ALL terminal outcomes — the CallStatus field in
        # the callback payload will be: completed | busy | no-answer | failed | canceled
        # Our handler in routers/calls.py maps every one of those to an AgentSessionStatus.
        status_callback_event=["initiated", "ringing", "answered", "completed"],
    )

    log.info("call created by Twilio", call_sid=call.sid, session_id=session.session_id)
    return call.sid


# ─── Call termination ─────────────────────────────────────────────────────────


async def terminate_call(call_sid: str) -> bool:
    """
    Terminate an active Twilio call by setting its status to 'completed'.

    Uses asyncio.to_thread so the synchronous Twilio client doesn't block
    the event loop.  Returns True on success, False if credentials are absent
    or the Twilio API call fails.
    """
    import asyncio

    client = _twilio_client()
    if not client:
        log.warning("Twilio credentials not set — cannot terminate call", call_sid=call_sid)
        return False
    try:
        await asyncio.to_thread(
            lambda: client.calls(call_sid).update(status="completed")
        )
        log.info("call terminated via Twilio REST API", call_sid=call_sid)
        return True
    except Exception as exc:
        log.error("failed to terminate call", call_sid=call_sid, error=str(exc))
        return False


# ─── TwiML builder ────────────────────────────────────────────────────────────


def build_twiml(session: SessionState) -> str:
    """
    Build the TwiML XML response served to Twilio when the call is answered.

    Only opens a bidirectional WebSocket Media Stream — NO <Say> or pre-recorded
    audio.  All speech (greeting, questions, prompts) is generated by the AI
    agent and pushed over the WebSocket in Phase 3 (Deepgram STT + TTS).

    The WebSocket URL is derived from AGENT_SERVICE_BASE_URL:
      http(s)://host  →  ws(s)://host/twilio/stream/{session_id}
    """
    base = settings.AGENT_SERVICE_BASE_URL.rstrip("/")
    ws_base = base.replace("https://", "wss://").replace("http://", "ws://")
    stream_url = f"{ws_base}/twilio/stream/{session.session_id}"

    response = VoiceResponse()

    # Connect call audio to our WebSocket stream — this is the ONLY action.
    # Twilio keeps the call alive as long as the WebSocket remains open.
    connect = Connect()
    stream = Stream(url=stream_url)
    stream.parameter(name="session_id", value=session.session_id)
    connect.append(stream)
    response.append(connect)

    return str(response)
