"""
Quick-Start Workflow Templates

Pre-configured workflows for common KYC / verification use cases.
Clients can select these and customize them.
"""

from typing import Any


WORKFLOW_TEMPLATES: list[dict[str, Any]] = [

    # ─── 1. Basic Individual KYC ──────────────────────────────────────────────
    {
        "template_key": "basic_individual_kyc",
        "name": "Basic Individual KYC",
        "description": "Standard individual KYC as per RBI KYC Master Directions. Collects identity proof, address proof, and a recent photograph.",
        "category": "kyc",
        "welcome_message": "Hello! I'm calling to complete your KYC verification. This will take about 5 minutes. Please have your Aadhaar and PAN card ready.",
        "completion_message": "Thank you! Your KYC documents have been successfully submitted. We will notify you once the verification is complete within 24 hours.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 30,
        "documents": [
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card",
                "document_category": "identity",
                "description": "12-digit Aadhaar number required for identity verification",
                "is_required": True,
                "criteria_text": "Aadhaar must not be masked. Name must match the application. Should not be a photocopy.",
                "instructions": "Please upload the front and back of your Aadhaar card as a single PDF or two separate images.",
                "order_index": 0,
            },
            {
                "document_type_key": "pan_card",
                "display_name": "PAN Card",
                "document_category": "identity",
                "description": "PAN card for income tax identification",
                "is_required": True,
                "criteria_text": "PAN must be valid and name must match Aadhaar. Photo should be clearly visible.",
                "instructions": "Upload a clear image of your PAN card. Ensure all details are readable.",
                "order_index": 1,
            },
            {
                "document_type_key": "electricity_bill",
                "display_name": "Recent Address Proof",
                "document_category": "address",
                "description": "Any recent utility bill or bank statement showing current address",
                "is_required": True,
                "criteria_text": "Document must not be older than 3 months. Address must match the application form.",
                "instructions": "Upload a utility bill (electricity, water, or gas) or bank statement not older than 3 months.",
                "order_index": 2,
            },
        ],
        "questions": [
            {
                "question_text": "Is the address on your Aadhaar card the same as your current residential address?",
                "question_type": "yes_no",
                "is_required": True,
                "order_index": 0,
            },
            {
                "question_text": "Are you a Politically Exposed Person (PEP) or a relative of a PEP?",
                "question_type": "yes_no",
                "is_required": True,
                "helper_text": "A Politically Exposed Person (PEP) holds or has held a prominent public position.",
                "order_index": 1,
            },
            {
                "question_text": "What is your primary source of income?",
                "question_type": "multiple_choice",
                "options": ["Salary / Employment", "Business / Self-Employed", "Investments / Rental Income", "Pension / Retirement", "Other"],
                "is_required": True,
                "order_index": 2,
            },
        ],
    },

    # ─── 2. Home Loan KYC ─────────────────────────────────────────────────────
    {
        "template_key": "home_loan_kyc",
        "name": "Home Loan Application KYC",
        "description": "Comprehensive document collection for home loan applications. Covers identity, address, income, and property documents.",
        "category": "loan",
        "welcome_message": "Hello! I'm calling to collect documents for your home loan application. Please have your identity documents, income proof, and property documents ready.",
        "completion_message": "Thank you! All your documents for the home loan application have been submitted. Our team will review them and get back to you within 2-3 business days.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 60,
        "documents": [
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Name must match loan application. Both sides required.",
                "order_index": 0,
            },
            {
                "document_type_key": "pan_card",
                "display_name": "PAN Card",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Must be valid. Name must match Aadhaar.",
                "order_index": 1,
            },
            {
                "document_type_key": "passport",
                "display_name": "Passport (Optional - for NRI applicants)",
                "document_category": "identity",
                "is_required": False,
                "criteria_text": "Must be valid and not expired.",
                "order_index": 2,
            },
            {
                "document_type_key": "salary_slip",
                "display_name": "Last 3 Months Salary Slips",
                "document_category": "income",
                "is_required": True,
                "criteria_text": "Must be from the last 3 months. Must be stamped/signed by employer. Gross salary visible.",
                "instructions": "Upload salary slips for the last 3 consecutive months.",
                "order_index": 3,
            },
            {
                "document_type_key": "form_16",
                "display_name": "Form 16 (Latest)",
                "document_category": "income",
                "is_required": True,
                "criteria_text": "Must be for the latest financial year. Issued by current employer.",
                "order_index": 4,
            },
            {
                "document_type_key": "bank_statement_6months",
                "display_name": "Bank Statement (6 Months)",
                "document_category": "income",
                "is_required": True,
                "criteria_text": "Must be from the salary account. Last 6 months. Bank stamped or from net banking.",
                "order_index": 5,
            },
            {
                "document_type_key": "sale_deed",
                "display_name": "Property Sale Agreement / Allotment Letter",
                "document_category": "property",
                "is_required": True,
                "criteria_text": "Must be registered. Applicant's name must match identity documents.",
                "order_index": 6,
            },
            {
                "document_type_key": "property_tax_document",
                "display_name": "Property Tax Receipt",
                "document_category": "property",
                "is_required": False,
                "criteria_text": "Latest receipt. Must show property address.",
                "order_index": 7,
            },
        ],
        "questions": [
            {
                "question_text": "What is your employment type?",
                "question_type": "multiple_choice",
                "options": ["Salaried - Private Sector", "Salaried - Government / PSU", "Self-Employed Professional", "Self-Employed Business", "NRI"],
                "is_required": True,
                "order_index": 0,
            },
            {
                "question_text": "What is your approximate monthly gross income (in INR)?",
                "question_type": "number",
                "is_required": True,
                "helper_text": "Enter your gross monthly income before deductions.",
                "validation_rules": {"min": 0, "max": 100000000},
                "order_index": 1,
            },
            {
                "question_text": "Is the property under construction or ready to move in?",
                "question_type": "multiple_choice",
                "options": ["Ready to Move In (Resale)", "Ready to Move In (New)", "Under Construction", "Plot Purchase"],
                "is_required": True,
                "order_index": 2,
            },
            {
                "question_text": "Do you have any existing EMIs or outstanding loans?",
                "question_type": "yes_no",
                "is_required": True,
                "order_index": 3,
            },
        ],
    },

    # ─── 3. Insurance Premium Claim ───────────────────────────────────────────
    {
        "template_key": "insurance_claim",
        "name": "Insurance Claim Document Verification",
        "description": "Document verification workflow for health / life insurance premium claims. Collects identity, medical, and supporting documents.",
        "category": "insurance",
        "welcome_message": "Hello! I'm calling about your insurance claim. I'll guide you through uploading the required documents. Please have your policy details and medical documents ready.",
        "completion_message": "Thank you for submitting your documents. Your insurance claim documents have been received. Our team will process them within 5-7 working days.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 45,
        "documents": [
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card (Claimant)",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Claimant's Aadhaar must match policy records.",
                "order_index": 0,
            },
            {
                "document_type_key": "previous_insurance_policy",
                "display_name": "Insurance Policy Document",
                "document_category": "medical",
                "is_required": True,
                "criteria_text": "Policy must be active (not expired) at the time of claim. Policy number must match claim form.",
                "order_index": 1,
            },
            {
                "document_type_key": "hospital_bills",
                "display_name": "Original Hospital / Medical Bills",
                "document_category": "medical",
                "is_required": True,
                "criteria_text": "All bills must be originals or certified copies. Must be from the treatment period. Must be itemized.",
                "instructions": "Upload all medical bills. If multiple bills, combine into a single PDF.",
                "order_index": 2,
            },
            {
                "document_type_key": "discharge_summary",
                "display_name": "Hospital Discharge Summary",
                "document_category": "medical",
                "is_required": True,
                "criteria_text": "Must be issued by the treating hospital. Doctor's signature and hospital stamp required.",
                "order_index": 3,
            },
            {
                "document_type_key": "medical_reports",
                "display_name": "Diagnostic Reports & Prescriptions",
                "document_category": "medical",
                "is_required": False,
                "criteria_text": "Lab reports, X-rays, scan reports from the treatment period.",
                "order_index": 4,
            },
            {
                "document_type_key": "bank_statement_address",
                "display_name": "Bank Account Details (for reimbursement)",
                "document_category": "address",
                "is_required": True,
                "criteria_text": "Cancelled cheque or bank passbook showing account number and IFSC. Account must be in claimant's name.",
                "order_index": 5,
            },
        ],
        "questions": [
            {
                "question_text": "What type of claim is this?",
                "question_type": "multiple_choice",
                "options": ["Health Insurance - Hospitalization", "Health Insurance - Day Care", "Life Insurance - Death Claim", "Accidental Claim", "Critical Illness Claim"],
                "is_required": True,
                "order_index": 0,
            },
            {
                "question_text": "Was the hospitalization planned (pre-authorized) or an emergency?",
                "question_type": "multiple_choice",
                "options": ["Planned / Pre-authorized", "Emergency"],
                "is_required": True,
                "order_index": 1,
            },
            {
                "question_text": "What is the total claimed amount (in INR)?",
                "question_type": "number",
                "is_required": True,
                "validation_rules": {"min": 0, "max": 100000000},
                "order_index": 2,
            },
            {
                "question_text": "Is the claimant the same person as the insured, or a nominee / dependent?",
                "question_type": "multiple_choice",
                "options": ["Insured Person (Self)", "Nominee / Legal Heir", "Dependent Family Member"],
                "is_required": True,
                "order_index": 3,
            },
        ],
    },

    # ─── 4. Business / MSME KYC ───────────────────────────────────────────────
    {
        "template_key": "business_kyc",
        "name": "Business / MSME KYC",
        "description": "KYC verification for businesses, startups, and MSMEs. Collects entity documents, director/partner KYC, and financial documents.",
        "category": "kyc",
        "welcome_message": "Hello! I'm calling to complete the KYC for your business. Please have your business registration documents, GST certificate, and director/partner identity documents ready.",
        "completion_message": "Thank you! Your business KYC documents have been submitted. Verification will be completed within 3-5 business days.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 60,
        "documents": [
            {
                "document_type_key": "gst_certificate",
                "display_name": "GST Registration Certificate",
                "document_category": "business",
                "is_required": True,
                "criteria_text": "GST must be active. Business name must match registration documents.",
                "order_index": 0,
            },
            {
                "document_type_key": "certificate_of_incorporation",
                "display_name": "Certificate of Incorporation / Registration",
                "document_category": "business",
                "is_required": True,
                "criteria_text": "For companies: CoI from MCA. For partnerships: Partnership Deed. For proprietorships: Trade License or Udyam Certificate.",
                "order_index": 1,
            },
            {
                "document_type_key": "msme_registration",
                "display_name": "Udyam / MSME Registration",
                "document_category": "business",
                "is_required": False,
                "order_index": 2,
            },
            {
                "document_type_key": "pan_card",
                "display_name": "Business PAN Card",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "PAN in entity name. Must be active.",
                "order_index": 3,
            },
            {
                "document_type_key": "bank_statement_12months",
                "display_name": "Business Bank Statement (12 Months)",
                "document_category": "income",
                "is_required": True,
                "criteria_text": "Current account statement. Bank stamped. Last 12 months.",
                "order_index": 4,
            },
            {
                "document_type_key": "ca_certified_financials",
                "display_name": "Audited Financial Statements",
                "document_category": "income",
                "is_required": True,
                "criteria_text": "Last 2 years P&L and Balance Sheet. CA certified. UDIN mentioned.",
                "order_index": 5,
            },
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card (Authorized Signatory / Director)",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Aadhaar of authorized signatory or majority director.",
                "order_index": 6,
            },
        ],
        "questions": [
            {
                "question_text": "What is the legal structure of your business?",
                "question_type": "multiple_choice",
                "options": ["Sole Proprietorship", "Partnership Firm", "LLP", "Private Limited Company", "Public Limited Company", "NGO / Trust / Society"],
                "is_required": True,
                "order_index": 0,
            },
            {
                "question_text": "How many years has the business been in operation?",
                "question_type": "multiple_choice",
                "options": ["Less than 1 year", "1-3 years", "3-5 years", "More than 5 years"],
                "is_required": True,
                "order_index": 1,
            },
            {
                "question_text": "What is your approximate annual turnover (in INR)?",
                "question_type": "number",
                "is_required": True,
                "validation_rules": {"min": 0, "max": 10000000000},
                "order_index": 2,
            },
        ],
    },

    # ─── 5. Vehicle Loan KYC ──────────────────────────────────────────────────
    {
        "template_key": "vehicle_loan_kyc",
        "name": "Vehicle Loan KYC",
        "description": "Document collection for two-wheeler and four-wheeler loan applications.",
        "category": "loan",
        "welcome_message": "Hello! I'm calling to collect documents for your vehicle loan application. Please keep your identity documents, income proof, and vehicle quotation handy.",
        "completion_message": "Thank you! Your vehicle loan documents have been submitted. We'll process your application and contact you within 24 hours.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 30,
        "documents": [
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Name must match loan application. Both sides required.",
                "order_index": 0,
            },
            {
                "document_type_key": "pan_card",
                "display_name": "PAN Card",
                "document_category": "identity",
                "is_required": True,
                "order_index": 1,
            },
            {
                "document_type_key": "driving_license",
                "display_name": "Driving License",
                "document_category": "identity",
                "is_required": True,
                "criteria_text": "Must be valid and not expired. Should cover the vehicle category being purchased.",
                "order_index": 2,
            },
            {
                "document_type_key": "salary_slip",
                "display_name": "Salary Slip (Last 3 Months)",
                "document_category": "income",
                "is_required": True,
                "order_index": 3,
            },
            {
                "document_type_key": "bank_statement_6months",
                "display_name": "Bank Statement (6 Months)",
                "document_category": "income",
                "is_required": True,
                "order_index": 4,
            },
        ],
        "questions": [
            {
                "question_text": "What type of vehicle are you purchasing?",
                "question_type": "multiple_choice",
                "options": ["Two-Wheeler", "Four-Wheeler (Hatchback/Sedan)", "Four-Wheeler (SUV/MUV)", "Commercial Vehicle"],
                "is_required": True,
                "order_index": 0,
            },
            {
                "question_text": "Is this a new vehicle or a used/pre-owned vehicle?",
                "question_type": "multiple_choice",
                "options": ["New Vehicle", "Used / Pre-owned Vehicle"],
                "is_required": True,
                "order_index": 1,
            },
        ],
    },

    # ─── 6. Background Verification (Employment) ─────────────────────────────
    {
        "template_key": "employment_bgv",
        "name": "Employment Background Verification",
        "description": "Pre-employment background check covering identity, education, and previous employment verification.",
        "category": "background_check",
        "welcome_message": "Hello! I'm calling to complete your pre-employment background verification. This will take about 10 minutes. Please have your documents ready.",
        "completion_message": "Thank you! Your background verification documents have been collected. The verification report will be available within 3-5 business days.",
        "max_retry_attempts": 3,
        "session_timeout_minutes": 30,
        "documents": [
            {
                "document_type_key": "aadhaar_card",
                "display_name": "Aadhaar Card",
                "document_category": "identity",
                "is_required": True,
                "order_index": 0,
            },
            {
                "document_type_key": "pan_card",
                "display_name": "PAN Card",
                "document_category": "identity",
                "is_required": True,
                "order_index": 1,
            },
            {
                "document_type_key": "educational_certificate",
                "display_name": "Highest Qualification Certificate",
                "document_category": "other",
                "is_required": True,
                "criteria_text": "Original degree or diploma certificate from recognized institution. Must match the qualification mentioned in CV.",
                "order_index": 2,
            },
            {
                "document_type_key": "marksheet",
                "display_name": "Final Year Marksheet",
                "document_category": "other",
                "is_required": True,
                "order_index": 3,
            },
            {
                "document_type_key": "appointment_letter",
                "display_name": "Previous Employment Offer / Appointment Letter",
                "document_category": "income",
                "is_required": False,
                "criteria_text": "From most recent previous employer. Must show designation and joining date.",
                "order_index": 4,
            },
        ],
        "questions": [
            {
                "question_text": "How many years of total work experience do you have?",
                "question_type": "number",
                "is_required": True,
                "validation_rules": {"min": 0, "max": 50},
                "order_index": 0,
            },
            {
                "question_text": "Have you ever been terminated from a previous job for misconduct or disciplinary reasons?",
                "question_type": "yes_no",
                "is_required": True,
                "order_index": 1,
            },
            {
                "question_text": "Do you have any pending criminal cases or convictions?",
                "question_type": "yes_no",
                "is_required": True,
                "order_index": 2,
            },
            {
                "question_text": "Have all details in your CV / resume been accurately represented?",
                "question_type": "yes_no",
                "is_required": True,
                "order_index": 3,
            },
        ],
    },
]

# Build quick-lookup map by template_key
TEMPLATE_MAP: dict[str, dict] = {t["template_key"]: t for t in WORKFLOW_TEMPLATES}


def get_template(key: str) -> dict | None:
    return TEMPLATE_MAP.get(key)
